repos:
  - repo: local
    hooks:
      - id: git-cliff
        name: generate changelog
        language: system
        entry: bash -c 'git cliff --unreleased --prepend CHANGELOG.md && git add CHANGELOG.md'
        stages: [pre-commit]
        always_run: true
        pass_filenames: false
